export enum ElementEnum {
    ADD_QUESTION_ACTION = "add-question-action",
    ADD_QUESTION_BLOCK = "add-question-block",
    FORM_TITLE_BLOCK = "form-title-block",
    FORM_TITLE_ACTION = "form-title-action",
    FORM_DESCRIPTION_BLOCK = "form-description-block",
    FORM_DESCRIPTION_ACTION = "form-description-action",
    QUESTION_TITLE_ACTION = "question-title-action",
    QUESTION_TITLE_BLOCK = "question-title-block",
    QUESTION_TYPE_ACTION = "question-type-action",
    QUESTION_TYPE_BLOCK = "question-type-block",
    OPTIONS_BLOCK = "options-block",
    OPTIONS_ACTION = "options-action",
    QUESTION_BLOCK = "question-block",
    QUESTION_ACTION = "question-action",
    LOGIN_BUTTON_BLOCK = "login-button-block",
    LOGIN_BUTTON_ACTION = "login-button-action",
    SHARE_RESPONSES_ACTION = "share-responses-action",
    SUBSCRIPTION_ACTION = "subscription-action"
}
