export enum ElementEnum {
    ADD_QUESTION_ACTION = "add-question-action",
    ADD_QUESTION_BLOCK = "add-question-block",
    FORM_TITLE_BLOCK = "form-title-block",
    FORM_TITLE_ACTION = "form-title-action",
    FORM_DESCRIPTION_BLOCK = "form-description-block",
    FORM_DESCRIPTION_ACTION = "form-description-action",
    QUESTION_TITLE_ACTION = "question-title-action",
    QUESTION_TITLE_BLOCK = "question-title-block",
    QUESTION_TYPE_ACTION = "question-type-action",
    QUESTION_TYPE_BLOCK = "question-type-block",
    OPTIONS_BLOCK = "options-title-block",
    OPTIONS_ACTION = "options-title-action",
    QUESTION_BLOCK = "question-block",
    QUESTION_ACTION = "question-action",
    LOGIN_BUTTON_BLOCK = "login-button-block",
    LOGIN_BUTTON_ACTION = "login-button-action",
    SHARE_RESPONSES_ACTION = "share-responses-action",
    SHARE_RESPONSES_BLOCK = "share-responses-block",
    SUBSCRIPTION_ACTION = "subscription-action",
    SUBSCRIPTION_BLOCK = "subscription-block",
    ADD_OPTION_BLOCK = "add-option-block",
    ADD_OPTION_ACTION = "add-option-action",
    QUESTION_NAME = 'QuestionName',
    QUESTION_TYPE = 'QuestionType',
    INPUT_FIELD = 'inputField',
}
